num=[1,2,3,4,5,6,7,8,9,10]
removen=num.remove(5)
print(num)
appendn=num.append(1)
print(num)
insertn=num.insert(0,0)
print(num)
sortn=num.sort(reverse=True)
print(num)
indexn=num.index(7)
print(indexn)
num.append([6, 7])
print(num)