num_1=float(input("Enter the first number: "))
num_2=float(input("Enter the second number: "))
print(f'{num_1}=={num_2}:',num_1==num_2)
print(f'{num_1}!={num_2}:{num_1!=num_2}')
print(f'{num_1}>{num_2}:{num_1>num_2}')
print(f'{num_1}<{num_2}:{num_1<num_2}')
print(f'{num_1}>={num_2}:{num_1>=num_2}')
print(f'{num_1}<={num_2}:{num_1<=num_2}')